# Generated by Django 3.2.7 on 2021-10-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('firstName', models.CharField(default='', max_length=50, null=True)),
                ('lastName', models.CharField(default='', max_length=50, null=True)),
                ('age', models.IntegerField(default='', null=True)),
                ('gender', models.CharField(default='', max_length=50, null=True)),
                ('woreda', models.CharField(default='', max_length=50, null=True)),
                ('zone', models.CharField(default='', max_length=50, null=True)),
                ('region', models.CharField(default='', max_length=50, null=True)),
                ('job', models.CharField(default='', max_length=50, null=True)),
                ('patientId', models.CharField(default='', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryMeasurement',
            fields=[
                ('patientInformation', models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.patientinformation')),
                ('sbp', models.IntegerField(default='', null=True)),
                ('fbs', models.IntegerField(default='', null=True)),
                ('hw', models.CharField(default='', max_length=50, null=True)),
                ('physcialActivity', models.CharField(default='', max_length=50, null=True)),
                ('diabeticFamilyHistory', models.CharField(default='', max_length=50, null=True)),
                ('impairedGlucose', models.CharField(default='', max_length=50, null=True)),
                ('autoImune', models.CharField(default='', max_length=50, null=True)),
                ('acuteWeightLoss', models.CharField(default='', max_length=50, null=True)),
                ('hypertension', models.CharField(default='', max_length=50, null=True)),
                ('bmi', models.CharField(default='', max_length=50, null=True)),
                ('monofilamenTest', models.CharField(default='', max_length=50)),
                ('neurologicPain', models.CharField(default='', max_length=50)),
                ('disautonomia', models.CharField(default='', max_length=50)),
                ('footDeformity', models.CharField(default='', max_length=50)),
                ('pad', models.CharField(default='', max_length=50)),
                ('decreasedVision', models.CharField(default='', max_length=50)),
                ('floaters', models.CharField(default='', max_length=50)),
                ('retinalScreeningResult', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('patientInformation', models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.patientinformation')),
                ('diabetic', models.CharField(default='', max_length=50)),
                ('risk', models.CharField(default='', max_length=50)),
                ('neuropathy', models.CharField(default='', max_length=50)),
                ('opthalmopathy', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
